# Generated by Django 5.0.6 on 2024-06-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
